name: Fetch IMDb Data

on:
  workflow_dispatch: # Allows manual trigger
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight

jobs:
  fetch-imdb:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      - name: Install R packages
        run: |
          install.packages(c("httr", "jsonlite", "dplyr"))

      - name: Run data fetch script
        run: Rscript fetch_imdb_data.R

      - name: Push updated data
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update IMDb data"
          file_pattern: |
            data/*.json
            data/posters/*.jpg
